---
lang: es
---
<!-- LTeX: language = es-ES -->

::: {.content-visible unless-format="pdf"}
{{< include macros.qmd >}}
:::
# Sucesiones de números reales

Las sucesiones de números reales son claves para comprender el concepto de límite que es fundamental en el Análisis Matemático. En este capítulo se presenta el concepto de sucesión de números reales, el concepto de límite y algunos resultados importantes sobre la convergencia de sucesiones.

## Concepto de sucesión

:::{#def-sucesion}
## Sucesión de números reales
Una _sucesión de números reales_ es una aplicación $x:\mathbb{N}\to \mathbb{R}$ que asigna a cada número natural un número real, conocido como _término de la sucesión_.
:::

Es habitual referirse a una sucesión con la notación $(x_n)_{n=1}^\infty$, donde $x_n=x(n)$ con $n\in\mathbb{N}$, o simplemente con $x_n$.

:::{#exm-sucesion1}
La sucesión $\left(\frac{1}{n}\right)_{n=1}^\infty$ está formada por los términos $\frac{1}{1}, \frac{1}{2}, \frac{1}{3}, \ldots$.
:::

:::{.callout-caution}
No hay que confundir los términos de una sucesión $(x_n)_{n=1}^\infty$, que tienen orden, con el conjunto de los valores de la sucesión $\{x_n:n\in\mathbb{N}\}$ que no tiene orden.
:::

:::{#exm-sucesion2}
La sucesión $\left((-1)^n\right)_{n=1}^\infty$ está formada por los términos $-1,1,-1,1,\ldots$, mientras que $\{x_n:n\in\mathbb{N}\}=\{-1,1\}$.
:::

Las operaciones aritméticas de los números reales se pueden extrapolar a las sucesiones aplicándolas término a término. 

:::{#def-operaciones-sucesiones}
## Operaciones con sucesiones
Dadas dos sucesiones de números reales $(x_n)_{n=1}^\infty$ e $(y_n)_{n=1}^\infty$, se definen las siguientes operaciones:

- _Suma:_ $(x_n)_{n=1}^\infty + (y_n)_{n=1}^\infty = (x_n+y_n)_{n=1}^\infty$.

- _Diferencia:_ $(x_n)_{n=1}^\infty - (y_n)_{n=1}^\infty = (x_n-y_n)_{n=1}^\infty$.

- _Producto:_ $(x_n)_{n=1}^\infty (y_n)_{n=1}^\infty = (x_ny_n)_{n=1}^\infty$.

- _División:_ $\dfrac{(x_n)_{n=1}^\infty}{(y_n)_{n=1}^\infty} = \left(\dfrac{x_n}{y_n}\right)_{n=1}^\infty$, siempre y cuando $y_n\neq 0$ $\forall n\in\mathbb{N}$.

- _Producto por escalar:_ $c(x_n)_{n=1}^\infty = (cx_n)_{n=1}^\infty$.

:::

:::{#exm-operaciones-sucesiones}
Dadas las sucesiones $(n)_{n=1}^\infty$ y $((-1)^n)_{n=1}^\infty$ se tiene:

\begin{align*}
(n)_{n=1}^\infty + ((-1)^n)_{n=1}^\infty &= (n + (-1)^n)_{n=1}^\infty = (0, 3, 2, 5, 4, \ldots)\\
(n)_{n=1}^\infty ((-1)^n)_{n=1}^\infty &= (n (-1)^n)_{n=1}^\infty = (-1, 2, -3, 4, -5, \ldots)
\end{align*}
:::

## Límite de una sucesión

:::{#def-limite-sucesion}
## Límite de una sucesión
Dada una sucesión $(x_n)_{n=1}^\infty$, se dice que un número $x\in\mathbb{R}$ es el _límite de la sucesión_, si para cada $\varepsilon>0$ existe un $k\in\mathbb{N}$ a partir del cuál todos los términos de la sucesión caen en el entorno $(x-\varepsilon, x+\varepsilon)$, es decir, $|x_n-x|<\varepsilon$ $\forall n\geq k$.

Si $x$ es el límite de la sucesión, se dice que la suceción _converge_ a $x$, y se denota $\lim_{n\to\infty}x_n = x$.
:::

Si una sucesión tiene límite se dice que es _convergente_, y en caso contrario se dice que es _divergente_.

:::{#exm-limite-sucesion}
La sucesión $(\frac{1}{n})_{n=1}^\infty$ es convergente y $\lim_{n\to\infty}\frac{1}{n} = 0$, ya que para cualquier $\varepsilon>0$, por la @thm-propiedad-arquimediana, se tiene que existe un $k\in\mathbb{N}$, tal que $\frac{1}{k}<\varepsilon$, de manera que para cualquier $n>k$, se tiene $|\frac{1}{n}-0| = \frac{1}{n} <\frac{1}{k}<\varepsilon$.

Sin embargo, la sucesión $(n)_{n=1}^\infty$ diverge.
:::


:::{#thm-unicidad-limite-sucesion}
Una sucesión de números reales puede tener a lo sumo un límite.
:::

:::{.callout-note collapse="true"}
## Demostración
:::{.proof}
Lo probaremos por reducción al absurdo. Supongamos que $(x_n)_{n=1}^\infty$ converge a $x$ e $y$ con $x\neq y$.
Entonces existe un $\varepsilon>0$ tal que los entornos $(x-\varepsilon,x+\varepsilon)$ e $(y-\varepsilon,y+\varepsilon)$ son disjuntos. Ahora bien, por ser $\lim_{n\to\infty}x_n = x$ existe un $k_1\in\mathbb{N}$ tal que $x_n\in(x-\varepsilon,x+\varepsilon)$ $\forall n\geq k_1$, y por ser $\lim_{n\to\infty}y_n = y$ existe un $k_2\in\mathbb{N}$ tal que $x_n\in(y-\varepsilon,y+\varepsilon)$ $\forall n\geq k_2$. Basta tomar $k=\max(k_1,k_2)$ para ver que $x_k$ pertenece a ambos entornos, lo cual contradice que sean disjuntos. Por tanto, debe ser $x=y$.
:::
:::

:::{#def-cola-sucesion}
## Cola de una sucesión
Dada una sucesión de números reales $(x_n)_{n=1}^\infty$ y $m\in\mathbb{N}$, se define la _cola_ $m$ de la sucesión, como la sucesión $(x_{m+n})_{n=1}^\infty = (x_{m+1}, x_{m+2},\ldots)$.
:::

:::{#prp-convergencia-cola-sucesion}
Dada una sucesión de números reales $(x_n)_{n=1}^\infty$ y $m\in\mathbb{N}$, la cola $(x_{m+n})_{n=1}^\infty$ converge si y solo si $(x_n)_{n=1}^\infty$ converge, y en tal caso, $\lim_{n\to\infty}x_n=\lim_{n\to\infty}x_{m+n}$.
:::

:::{.callout-note collapse="true"}
## Demostración
:::{.proof}
Supongamos que la cola $(x_{m+n})_{n=1}^\infty$ converge a $x$. Entonces, para cada $\varepsilon>0$, existe un $k_1\in\mathbb{N}$ tal que $|x_{m+n}-x|<\varepsilon$ $\forall n\geq k_1$. Tomando ahora $k=k_1+m\in\mathbb{N}$ se tiene que para cualquier $l\geq k$ $|x_l-x| = |x_{l-m+m}-x| = |x_{m+n}-x| < \varepsilon$ siendo $n=l-m$, ya que $l\geq k_1+m$ y $l-m\geq k_1$. Por tanto, $(x_n)_{n=1}^\infty$ converge a $x$.

Para probar la otra implicación, supongamos ahora que $(x_n)_{n=1}^\infty$ converge a $x$. Entonces, para cada $\varepsilon>0$, existe un $k\in\mathbb{N}$ tal que $|x_n-x|<\varepsilon$ $\forall n\geq k$. Pero como $m\in\mathbb{N}$, si $n\geq k$ también $m+n\geq k$, con lo que $|x_{m+n}-x|<\varepsilon$, y por consiguiente, $(x_{m+n})_{n=1}^\infty$ converge a $x$.
:::
:::

:::{#prp-convergencia-sucesion-acotada}
Sean $(x_n)_{n=1}^\infty$ y $(y_n)_{n=1}^\infty$ dos sucesiones de números reales tales que $(y_n)_{n=1}^\infty$ converge a 0. Si existe $x, c\in\mathbb{R}$ con $c>0$ tal que $|x_n-x| < c|y_n|$ $\forall n\in \mathbb{N}$, entonces $(x_n)_{n=1}^\infty$ converge a $x$.
:::

:::{.callout-note collapse="true"}
## Demostración
:::{.proof}
Dado $\varepsilon>0$, sea $\varepsilon'=\frac{\varepsilon}{c}>0$. Como $(y_n)_{n=1}^\infty$ converge a 0, existe $k\in\mathbb{N}$ tal que $|y_n-0|=|y_n|<\varepsilon'$ $\forall n\geq k$. Así pues, $\forall n\geq k$ se tiene que $|x_n-x|<c|y_n|<c\varepsilon'=c\frac{\varepsilon}{c}=\varepsilon$, por lo que $(x_n)_{n=1}^\infty$ converge a $x$.
:::
:::

:::{#exm-convergencia-sucesion-acotada}
Veamos que la sucesión $\left(\frac{1}{2^n}\right)_{n=1}^\infty$ converge a 0. Para cualquier $n\in\mathbb{N}$ se cumple que $0<n<2^n$, de donde se deduce $0<\frac{1}{2^n}<\frac{1}{n}$, lo que equivale a $|\frac{1}{2^n}-0|<\frac{1}{n}$. Así pues, aplicando el teorema anterior, se concluye que $\lim_{n\to\infty}\frac{1}{2^n}=0$.

Veamos ahora que $\lim_{n\to\infty}n^{1/n}=1$. Para cualquier $n\in\mathbb{N}$, con $n>1$, se cumple que $n^{1/n}>1$, de manera que se puede escribir $n^{1/n} = 1+k_n$, donde $k_n=n^{1/n}-1$. Aplicando ahora el teorema del binomio, se tiene que $0<k_n<\sqrt{2/n}$ $\forall n\in\mathbb{N}$. Por tanto, $|n^{1/n}-1| = k_n < \sqrt{2/n}=\sqrt{2}\frac{1}{\sqrt{n}}$, y como $\sqrt{2}>0$ y $\lim_{n\to\infty}\frac{1}{\sqrt{n}}=0$, por el teorema anterior se tiene que $\lim_{n\to\infty} n^{1/n} = 1$.
:::

:::{#def-sucesion-acotada}
## Sucesión acotada
Se dice que una sucesión de números reales $(x_n)_{n=1}^\infty$ está _acotada_ si existe $c>0$ tal que $|x_n|\leq c$ $\forall n\in\mathbb{N}$.
:::

:::{#thm-convergencia-sucesion-acotada}
Toda sucesión de números reales convergente está acotada.
:::

:::{.callout-note collapse="true"}
## Demostración
:::{.proof}
Sea $(x_n)_{n=1}^\infty$ una sucesión convergente a $x$. Entonces, si tomamos $\varepsilon=1$ existe un $k\in\mathbb{N}$ tal que  $|x_n-x|<1$ $\forall n\geq k$.

Por la desigualdad triangular (@prp-propiedades-valor-absoluto) se tiene que $|x_n|=|x_n-x+x|\leq |x_n-x|+|x|<1 + |x|$, de donde se deduce que $|x_n|<|x|+1$ $\forall n\geq k$. Si se toma $c=\max\{|x_1|,\ldots, |x_{k-1}|, |x|+1\}$ se tiene que si $n<k$ entonces $|x_n|\leq c$ y si $n\geq k$ entonces $|x_n| <|x|+1\leq c$, de modo que $\forall n\in\mathbb{N}$ $|x_n|\leq c$, por lo que $(x_n)_{n=1}^\infty$ está acotada.
:::
:::

:::{#exm-sucesion-acotada}
La sucesión $(n)_{n=1}^\infty$ diverge ya que no está acotada. Si estuviese acotada existiría un $c>0$ tal que $|n|\leq c$ $\forall n\in\mathbb{N}$, lo que infringe la propiedad arquimediana.
:::

:::{.callout-caution}
El otro sentido de la implicación no se cumple, es decir, no toda sucesión acotada es convergente. Por ejemplo, la sucesión $((-1)^n)_{n=1}^\infty$.
:::


:::{#prp-algebra-limites-sucesiones}
Sean $(x_n)_{n=1}^\infty$ y $(y_n)_{n=1}^\infty$ dos sucesiones de números reales tales que $(x_n)_{n=1}^\infty$ converge a $x$ e $(y_n)_{n=1}^\infty$ converge a $y$. Entonces se cumple:

a. $(x_n)_{n=1}^\infty$ + $(y_n)_{n=1}^\infty$ converge a $x+y$.

b. $(x_n)_{n=1}^\infty$ - $(y_n)_{n=1}^\infty$ converge a $x-y$.

c. $(x_n)_{n=1}^\infty$ $(y_n)_{n=1}^\infty$ converge a $xy$.

d. $c(x_n)_{n=1}^\infty$ converge a $cx$.

e. Si $y_n\neq 0$ $\forall n\in\mathbb{N}$ e $y\neq 0$, $\frac{(x_n)_{n=1}^\infty}{(y_n)_{n=1}^\infty}$ converge a $\frac{x}{y}$.
:::

:::{.callout-note collapse="true"}
## Demostración
:::{.proof}
Se deja como ejercicio.
:::
:::

:::{#exm-algebra-limites-sucesiones}
Veamos que la sucesión $\left(\frac{2n+1}{n+3}\right)_{n=1}^\infty$ converge a 2.

\begin{align*}
\lim_{n\to\infty}\frac{2n+1}{n+3} &=  \lim_{n\to\infty}\frac{2+\frac{1}{n}}{1+\frac{3}{n}} = \frac{\lim_{n\to\infty}2+\frac{1}{n}}{\lim_{n\to\infty}1+\frac{3}{n}} = \\ 
&=\frac{\lim_{n\to\infty} 2 + \lim_{n\to\infty}\frac{1}{n}}{\lim_{n\to\infty} 1 + \lim_{n\to\infty}\frac{3}{n}} = \frac{2+0}{1+0} = 2.
\end{align*}


:::

:::{#thm-compresion-sucesiones}
## Compresión de sucesiones convergentes
Dadas tres sucesiones de números reales $(x_n)_{n=1}^\infty$, $(y_n)_{n=1}^\infty$ y $(z_n)_{n=1}^\infty$, tales que $x_n\leq y_n\leq z_n$ $\forall n\in\mathbb{N}$, si $(x_n)_{n=1}^\infty$ y $(z_n)_{n=1}^\infty$ convergen a $x$, entonces $(y_n)_{n=1}^\infty$ converge a $x$.
:::

:::{.callout-note collapse="true"}
## Demostración
:::{.proof}
Supongamos que $\lim_{n\to\infty} x_n = \lim_{n\to\infty} z_n=x$ y sea $\varepsilon>0$. Si tomamos $\varepsilon_1=\frac{\varepsilon}{4}>0$, como $(z_n)_{n=1}^\infty$ converge a $x$, existe $k_1\in\mathbb{N}$ tal que $|z_n-x|<\varepsilon_1$ $\forall n\geq k_1$. Y si tomamos $\varepsilon_2 = \frac{\varepsilon}{2}>0$, como $(x_n)_{n=1}^\infty$ converge a $x$, existe $k_2\in\mathbb{N}$ tal que $|x_n-x|<\varepsilon_2$ $\forall n\geq k_2$. Entonces, si se toma $k=\max(k_1,k_2)$, se cumple que para cualquier $n\geq k$, 

\begin{align*}
|y_n-x| &= |y_n-z_n+z_n-x| \\
&\leq |y_n-z_n|+|z_n-x| \tag{prop.2.4 (f)}\\
&= z_n-y_n+|z_n-x| \\
&\leq z_n-x_n+|z_n-x| \\
&= |z_n-x_n|+|z_n-x| \\
&= |z_n-x+x-x_n|+|z_n-x| \\
&\leq |z_n-x|+|x-x_n|+|z_n-x| \\
&= 2|z_n-x|+|x-x_n| \tag{prop.2.4 (f)}\\
&= 2|z_n-x|+|x_n-x| \tag{prop.2.4 (b)}\\ 
&< 2\varepsilon_1+\varepsilon_2 = 2\frac{\varepsilon}{4}+\frac{\varepsilon}{2}=\varepsilon.
\end{align*}

Por tanto, $\lim_{n\to\infty} y_n=x$.
:::
:::

:::{#exm-compresion-sucesiones}
Veamos que la sucesión $\left(\frac{2n}{n^2+1}\right)_{n=1}^\infty$ converge a 0. Para ello basta con ver que 

$$
0\leq \frac{2n}{n^2+1} \leq \frac{2n}{n^2}\leq \frac{2}{n}\ \forall n\in\mathbb{N}
$$

y que $\lim_{n\to\infty} \frac{2}{n}=\lim_{n\to\infty} 0 = 0$, de manera que aplicando el teorema anterior de compresión se tiene que $\lim_{n\to\infty} \frac{2n}{n^2+1}=0$.

Veamos ahora que la sucesión $\left(\frac{\operatorname{sen}(n)}{n}\right)_{n=1}^\infty$ también converge a 0. De nuevo basta con ver que

$$
0\leq \frac{\operatorname{sen}(n)}{n} \leq \frac{1}{n}\ \forall n\in\mathbb{N}
$$

y que $\lim_{n\to\infty} \frac{1}{n}=\lim_{n\to\infty} 0 = 0$, de manera que aplicando el teorema anterior de compresión se tiene que $\lim_{n\to\infty} \frac{\operatorname{sen}(n)}{n}=0$.
:::

:::{#prp-limite-cociente-sucesiones}
Si $(x_n)_{n=1}^\infty$ es una sucesión de números reales estrictamente positivos tal que la sucesión  $\left(\frac{x_{n+1}}{x_n}\right)_{n=1}^\infty$ converge a $l<1$, entonces $(x_n)_{n=1}^\infty$ converge a 0.
:::

:::{.callout-note collapse="true"}
## Demostración
:::{.proof}
Sea $y$ tal que $l<y<1$ y tomemos $\varepsilon=y-l>0$. Como $\lim_{n\to\infty}\frac{x_{n+1}}{x_n}=l$, existe un $k\in\mathbb{N}$ tal que $|\frac{x_{n+1}}{x_n}-l|\leq \varepsilon$ $\forall n\geq k$, y por tanto, se tiene que para cualquier $n\geq k$,

\begin{align*}
|\frac{x_{n+1}}{x_n}-l|\leq \varepsilon &\Rightarrow
-\varepsilon<\frac{x_{n+1}}{x_n}-l\leq \varepsilon\\ 
&\Rightarrow \frac{x_{n+1}}{x_n}\leq l+\varepsilon=l+y-l=y\\ 
&\Rightarrow x_{n+1}<yx_n.
\end{align*}

Por consiguiente, si $m\in\mathbb{N}$ se cumple que $x_{k+m}<yx_{k+m-1}<r^2x_{k+m-2}<\cdots<r^mx_k$, de manera que $0<x_{k+m}<r^mx_k$ $\forall m\in\mathbb{N}$. Como $r<1$, $\lim_{m\to\infty}y^m=0$ y $\lim_{m\to\infty}r^mx_k=0$, y por el teorema de compresión (@thm-compresion-sucesiones) $\lim_{m\to\infty}x_{k+m}=0$. Finalmente, como $(x_{k+m})_{m=1}^\infty$ es una cola de la sucesión $(x_n)_{n=1}^\infty$ se tiene que $\lim_{n\to\infty}x_n=0$.
:::
:::

:::{#exm-limite-cociente-sucesiones}
Veamos que la sucesión $\left(\frac{n}{2^n}\right)_{n=1}^\infty$ converge a 0.

\begin{align*}
\lim_{n\to\infty}\frac{x_{n+1}}{x_n} &= \lim_{n\to\infty}\frac{\frac{n+1}{2^{n+1}}}{\frac{n}{2^n}} = \lim_{n\to\infty}\frac{1}{2}\frac{n+1}{n} \\ 
&= \lim_{n\to\infty} \frac{1}{2}\left(\frac{1}{n}+1\right) = \lim_{n\to\infty} \frac{1}{2}+\frac{1}{2n} \\
&= \lim_{n\to\infty} \frac{1}{2} + \lim_{n\to\infty} \frac{1}{2n} = \frac{1}{2}<1.
\end{align*}

Así pues, por la proposición anterior, $\lim_{n\to\infty}\frac{n}{2^n} = 0$.
:::
